name: rebuild static site
on: [push]
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: prepare
        run: npm install
      - name: build
        run: rm -rf out && npm run export && touch out/.nojekyll && echo -n odia.legal > out/CNAME
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
